Repository SproutJavaSesac/versebyverse-backend, pull requests merged in 2025-07, with the labels that each got.

#64 [#62]Chore(AI): PromptType 내용 수정, PromptTemplateLoaderTest 메서드 명 영문으로 수정
  src/main/java/today/sesac/shoutify/ai/prompt/PromptType.java
  src/test/java/today/sesac/shoutify/ai/prompt/PromptTemplateLoaderTest.java
Labels: Chore

#72 [#70]Deploy(test): 테스트 환경과 분리 위해 테스트 시 data.sql 실행하지 않도록 init mode 변경(h2 변경 X)
  src/test/resources/application.yml
Labels: Test, Deploy

#60 [#54] Feat(게시글): 게시글 단건 상세 조회 api 구현
  src/main/java/today/sesac/shoutify/post/controller/PostCommandController.java
  src/main/java/today/sesac/shoutify/post/controller/PostQueryController.java
  src/main/java/today/sesac/shoutify/post/dto/response/PostCreateResponseDto.java
  src/main/java/today/sesac/shoutify/post/dto/response/PostSingleQueryResponseDto.java
  src/main/java/today/sesac/shoutify/post/entity/Post.java
  src/main/java/today/sesac/shoutify/post/repository/PostRepository.java
  src/main/java/today/sesac/shoutify/post/service/PostQueryService.java
Labels: Feature

#75 [#68]Feat(comment): 프론트 확인 위해 댓글 생성, 삭제, 조회 API 구현
  src/main/java/today/sesac/shoutify/comment/controller/CommentController.java
  src/main/java/today/sesac/shoutify/comment/dto/request/CommentCreateRequestDto.java
  src/main/java/today/sesac/shoutify/comment/dto/response/CommentCreateResponseDto.java
  src/main/java/today/sesac/shoutify/comment/dto/response/CommentListResponseDto.java
  src/main/java/today/sesac/shoutify/comment/dto/response/CommentResponseDto.java
  src/main/java/today/sesac/shoutify/comment/entity/Comment.java
  src/main/java/today/sesac/shoutify/comment/exception/CommentErrorCode.java
  src/main/java/today/sesac/shoutify/comment/exception/CommentException.java
  src/main/java/today/sesac/shoutify/comment/repository/CommentRepository.java
  src/main/java/today/sesac/shoutify/comment/service/CommentService.java
  src/main/resources/data.sql
  src/test/java/today/sesac/shoutify/comment/controller/CommentControllerTest.java
Labels: Feature

#74 [#69] Feat(Member): 프론트 테스트 위한 로그인/마이페이지 임시 api 구현
  src/main/java/today/sesac/shoutify/auth/CustomLogoutSuccessHandler.java
  src/main/java/today/sesac/shoutify/auth/controller/AuthController.java
  src/main/java/today/sesac/shoutify/auth/dto/response/LoginStatusResponseDto.java
  src/main/java/today/sesac/shoutify/auth/service/CustomOAuth2UserService.java
  src/main/java/today/sesac/shoutify/global/config/SecurityConfig.java
  src/main/java/today/sesac/shoutify/member/controller/MemberController.java
  src/main/java/today/sesac/shoutify/member/dto/request/MyInfoEditRequestDto.java
  src/main/java/today/sesac/shoutify/member/dto/response/MyCommentListResponseDto.java
  src/main/java/today/sesac/shoutify/member/dto/response/MyCommentSummary.java
  src/main/java/today/sesac/shoutify/member/dto/response/MyInfoEditResponseDto.java
  src/main/java/today/sesac/shoutify/member/dto/response/MyInfoGetResponseDto.java
  src/main/java/today/sesac/shoutify/member/dto/response/MyPostListResponseDto.java
  src/main/java/today/sesac/shoutify/member/dto/response/MyPostSummary.java
  src/main/java/today/sesac/shoutify/member/entity/Member.java
  src/main/java/today/sesac/shoutify/member/service/MemberService.java
Labels: Feature

#85 [#84]Feat(member): 프론트 확인을 위한 회원 관련 기능 충돌 해결하기 위해 긴급 수정
  src/main/java/today/sesac/shoutify/member/service/MemberService.java
Labels: Feature

#78 [#76]Feat(비속어): 프론트 연동을 위한 ProfanityController 구현
  src/main/java/today/sesac/shoutify/profanity/controller/ProfanityController.java
  src/main/java/today/sesac/shoutify/profanity/dto/request/ProfanityRegisterRequestDto.java
  src/main/java/today/sesac/shoutify/profanity/dto/request/ProfanityUpdateRequestDto.java
  src/main/java/today/sesac/shoutify/profanity/dto/response/ProfanityListResponseWrapperDto.java
  src/main/java/today/sesac/shoutify/profanity/dto/response/ProfanityResponseDto.java
Labels: Feature

#92 [#55]Feat(scheduler): ranking에서 사용할 Scheduler Config 전역 설정
  src/main/java/today/sesac/shoutify/global/config/ScheduleConfig.java
Labels: Feature

#82 [#71]Feat(post): 조회 가능한 조건의 게시물 조회 메서드 구현 및 테스트
  src/main/java/today/sesac/versebyverse/post/entity/Post.java
  src/main/java/today/sesac/versebyverse/post/repository/PostRepository.java
  src/main/java/today/sesac/versebyverse/post/service/PostQueryService.java
  src/test/java/today/sesac/versebyverse/post/repository/PostRepositoryTest.java
  src/test/java/today/sesac/versebyverse/post/service/PostQueryServiceTest.java
Labels: Feature

#90 [#18]Feat(ranking): 일별 게시글 수 랭킹 생성 구현, member 탈퇴 필드 임시로 추가
  src/main/java/today/sesac/versebyverse/member/entity/Member.java
  src/main/java/today/sesac/versebyverse/post/dto/AuthorPostCountDto.java
  src/main/java/today/sesac/versebyverse/post/repository/PostRepository.java
  src/main/java/today/sesac/versebyverse/post/service/PostQueryService.java
  src/main/java/today/sesac/versebyverse/ranking/controller/RankingController.java
  src/main/java/today/sesac/versebyverse/ranking/dto/response/RankingListResponseDto.java
  src/main/java/today/sesac/versebyverse/ranking/dto/response/RankingSingleResponseDto.java
  src/main/java/today/sesac/versebyverse/ranking/entity/Ranking.java
  src/main/java/today/sesac/versebyverse/ranking/repository/RankingRepository.java
  src/main/java/today/sesac/versebyverse/ranking/service/RankingService.java
  src/main/resources/data.sql
Labels: Feature

#119 [#118]Feat(공통): data.sql 비속어 더미데이터 추가
  src/main/resources/data.sql
Labels: Feature

#102 [#57]Feat(comment): 댓글 생성 기능 구현, 조회에도 검증 추가
  src/main/java/today/sesac/versebyverse/comment/controller/CommentController.java
  src/main/java/today/sesac/versebyverse/comment/exception/CommentErrorCode.java
  src/main/java/today/sesac/versebyverse/comment/repository/CommentRepository.java
  src/main/java/today/sesac/versebyverse/comment/service/CommentService.java
  src/main/java/today/sesac/versebyverse/member/repository/MemberRepository.java
  src/main/java/today/sesac/versebyverse/member/service/MemberService.java
  src/main/java/today/sesac/versebyverse/post/repository/PostRepository.java
  src/main/java/today/sesac/versebyverse/post/service/PostQueryService.java
  src/main/resources/data.sql
  src/test/java/today/sesac/versebyverse/comment/controller/CommentControllerTest.java
Labels: Feature

#117 [#65]Feat(비속어): 비속어 등록 API, 커스텀익셉션 구현
  .gitignore
  src/main/java/today/sesac/versebyverse/profanity/controller/ProfanityController.java
  src/main/java/today/sesac/versebyverse/profanity/dto/request/ProfanityRegisterRequestDto.java
  src/main/java/today/sesac/versebyverse/profanity/dto/request/ProfanityUpdateRequestDto.java
  src/main/java/today/sesac/versebyverse/profanity/dto/response/ProfanityResponseDto.java
  src/main/java/today/sesac/versebyverse/profanity/exception/ProfanityErrorCode.java
  src/main/java/today/sesac/versebyverse/profanity/exception/ProfanityException.java
  src/main/java/today/sesac/versebyverse/profanity/repository/ProfanityRepository.java
  src/main/java/today/sesac/versebyverse/profanity/service/ProfanityService.java
Labels: Feature

#138 [#137]Feat(공통): GlobalExceptionHandler 빈 문자열 요청에 대한 enum 타입 유효성 검사 예외…
  src/main/java/today/sesac/versebyverse/global/advice/GlobalExceptionHandler.java
Labels: Feature

#94 [#63]Feat(post): 게시글 목록 조회 구현
  src/main/java/today/sesac/versebyverse/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/today/sesac/versebyverse/auth/service/UserPrincipal.java
  src/main/java/today/sesac/versebyverse/comment/repository/CommentRepository.java
  src/main/java/today/sesac/versebyverse/global/domain/Concept.java
  src/main/java/today/sesac/versebyverse/global/exception/AbstractBaseException.java
  src/main/java/today/sesac/versebyverse/member/entity/Member.java
  src/main/java/today/sesac/versebyverse/post/controller/PostQueryController.java
  src/main/java/today/sesac/versebyverse/post/dto/response/PageResponseDto.java
  src/main/java/today/sesac/versebyverse/post/dto/response/PostCreateResponseDto.java
  src/main/java/today/sesac/versebyverse/post/dto/response/PostSingleQueryResponseDto.java
  src/main/java/today/sesac/versebyverse/post/dto/response/PostSummaryResponseDto.java
  src/main/java/today/sesac/versebyverse/post/entity/Post.java
  src/main/java/today/sesac/versebyverse/post/repository/PostRepository.java
  src/main/java/today/sesac/versebyverse/post/service/PostCommandService.java
  src/main/java/today/sesac/versebyverse/post/service/PostQueryService.java
  src/main/java/today/sesac/versebyverse/profanity/entity/Profanity.java
  src/main/java/today/sesac/versebyverse/ranking/entity/Ranking.java
  src/main/java/today/sesac/versebyverse/ranking/service/RankingService.java
  src/main/java/today/sesac/versebyverse/ranking/util/DateTimeRangeCalculator.java
  src/test/java/today/sesac/versebyverse/ranking/util/DateTimeRangeCalculatorTest.java
Labels: Feature

#136 [#132]Feat(auth): 로그아웃 응답 공통 양식에 맞게 수정
  src/main/java/today/sesac/versebyverse/auth/CustomLogoutSuccessHandler.java
Labels: Feature

#135 [#133]Feat(auth): 로그인 상태 확인 api 로그인 되지 않았을 경우 반영
  src/main/java/today/sesac/versebyverse/auth/controller/AuthController.java
  src/main/java/today/sesac/versebyverse/auth/dto/response/LoginStatusResponseDto.java
  src/main/java/today/sesac/versebyverse/auth/service/AuthService.java
Labels: Feature

#144 [#143]Feat(auth): 회원가입/로그인 시 mockUserPrincipal으로 연결되는 로직 기존 userPrincipal로 복구
  src/main/java/today/sesac/versebyverse/auth/service/CustomOAuth2UserService.java
Labels: Feature
