Repository SproutJavaSesac/versebyverse-backend, pull requests merged in 2025-08, with the labels that each got.

#134 [#88] Feat(member): 회원 탈퇴 구현
  src/main/java/today/sesac/versebyverse/auth/controller/AuthController.java
  src/main/java/today/sesac/versebyverse/auth/service/SocialLoginService.java
  src/main/java/today/sesac/versebyverse/auth/service/UserPrincipal.java
  src/main/java/today/sesac/versebyverse/member/controller/MemberController.java
  src/main/java/today/sesac/versebyverse/member/entity/Member.java
  src/main/java/today/sesac/versebyverse/member/exception/MemberErrorCode.java
  src/main/java/today/sesac/versebyverse/member/exception/WithdrawFailureException.java
  src/main/java/today/sesac/versebyverse/member/repository/MemberRepository.java
  src/main/java/today/sesac/versebyverse/member/service/MemberService.java
Labels: Feature

#139 [#120]Feat(비속어): 비속어 수정 API구현
  src/main/java/today/sesac/versebyverse/profanity/controller/ProfanityController.java
  src/main/java/today/sesac/versebyverse/profanity/dto/request/ProfanityUpdateRequestDto.java
  src/main/java/today/sesac/versebyverse/profanity/entity/Profanity.java
  src/main/java/today/sesac/versebyverse/profanity/exception/ProfanityErrorCode.java
  src/main/java/today/sesac/versebyverse/profanity/exception/ProfanityException.java
  src/main/java/today/sesac/versebyverse/profanity/repository/ProfanityRepository.java
  src/main/java/today/sesac/versebyverse/profanity/service/ProfanityService.java
Labels: Feature

#150 [#145] 비속어 목록 조회
  src/main/java/today/sesac/versebyverse/profanity/controller/ProfanityController.java
  src/main/java/today/sesac/versebyverse/profanity/dto/response/ProfanityListResponseWrapperDto.java
  src/main/java/today/sesac/versebyverse/profanity/service/ProfanityService.java
Labels: Feature

#141 [#121]Feat(비속어): 비속어 삭제(Hard Delete) API 구현
  src/main/java/today/sesac/versebyverse/profanity/controller/ProfanityController.java
  src/main/java/today/sesac/versebyverse/profanity/repository/ProfanityRepository.java
  src/main/java/today/sesac/versebyverse/profanity/service/ProfanityService.java
Labels: Feature

#160 [#159]Fix(비속어): deleteProfanity() 중괄호 누락으로 인한 버그 수정
  src/main/java/today/sesac/versebyverse/profanity/service/ProfanityService.java
Labels: Bug

#153 [#112]Feat(AI): 게시글 등록 AI 글 변환 기능 추가
  src/main/java/today/sesac/versebyverse/ai/prompt/PromptType.java
  src/main/java/today/sesac/versebyverse/ai/service/AbstractAiService.java
  src/main/java/today/sesac/versebyverse/ai/service/PostAiService.java
  src/main/java/today/sesac/versebyverse/post/service/PostCommandService.java
  src/main/resources/templates/comment_concept_transform.md
  src/main/resources/templates/concept_transform.md
  src/main/resources/templates/post_concept_transform.md
Labels: Feature

#140 [#131]Feat(member): 마이 페이지 기능(내 정보 조회, 내 정보 수정, 내 게시글 조회, 내 댓글 조회) 리팩토링
  src/main/java/today/sesac/versebyverse/comment/repository/CommentRepository.java
  src/main/java/today/sesac/versebyverse/member/controller/MemberController.java
  src/main/java/today/sesac/versebyverse/member/dto/request/MyInfoEditRequestDto.java
  src/main/java/today/sesac/versebyverse/member/dto/response/MyCommentListResponseDto.java
  src/main/java/today/sesac/versebyverse/member/dto/response/MyCommentSummary.java
  src/main/java/today/sesac/versebyverse/member/dto/response/MyCommentSummaryDto.java
  src/main/java/today/sesac/versebyverse/member/dto/response/MyInfoEditResponseDto.java
  src/main/java/today/sesac/versebyverse/member/dto/response/MyInfoGetResponseDto.java
  src/main/java/today/sesac/versebyverse/member/dto/response/MyPostListResponseDto.java
  src/main/java/today/sesac/versebyverse/member/dto/response/MyPostSummary.java
  src/main/java/today/sesac/versebyverse/member/dto/response/MyPostSummaryDto.java
  src/main/java/today/sesac/versebyverse/member/entity/Member.java
  src/main/java/today/sesac/versebyverse/member/repository/MemberRepository.java
  src/main/java/today/sesac/versebyverse/member/service/MemberService.java
  src/main/java/today/sesac/versebyverse/post/repository/PostRepository.java
Labels: Refactor

#167 [#110]Deploy(test): sonarqube 이용해 테스트 커버리지 관리 위해 jacoco, sonarqube 추가
  build.gradle
Labels: Deploy

#163 [#91] Deploy(config): 배포 환경 설정(쿠키, CORS 설정)
  src/main/java/today/sesac/versebyverse/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/today/sesac/versebyverse/global/config/SecurityConfig.java
  src/main/java/today/sesac/versebyverse/global/config/WebConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: Deploy

#154 [#130]Feat(auth): 소셜 로그인 예외처리 추가
  src/main/java/today/sesac/versebyverse/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/today/sesac/versebyverse/auth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/today/sesac/versebyverse/auth/service/CustomOAuth2UserService.java
  src/main/java/today/sesac/versebyverse/global/config/SecurityConfig.java
  src/main/java/today/sesac/versebyverse/member/service/MemberService.java
Labels: Feature

#184 [#183]Bug(공통): 배포 후 엔티티와 db 타입 오류로 인해 코드 수정 및 yml에서 sql.init 주석
  src/main/java/today/sesac/versebyverse/comment/entity/Comment.java
  src/main/java/today/sesac/versebyverse/member/entity/Member.java
  src/main/java/today/sesac/versebyverse/post/entity/Post.java
  src/main/resources/application-local.yml
Labels: Bug

#188 [#187]Fix(공통): application-local.yml ddl-auto, data.sql 로드할 수 있게 주석 해제
  src/main/resources/application-local.yml
Labels: Bug

#185 [#142]Feat(comment): 관리자용 댓글 단건 조회 API 구현
  src/main/java/today/sesac/versebyverse/comment/controller/CommentController.java
  src/main/java/today/sesac/versebyverse/comment/dto/response/CommentSingleQueryForAdminResponseDto.java
  src/main/java/today/sesac/versebyverse/comment/repository/CommentRepository.java
  src/main/java/today/sesac/versebyverse/comment/service/CommentService.java
  src/main/java/today/sesac/versebyverse/post/service/PostQueryService.java
Labels: Feature

#169 [#151] 배지 엔티티 구현 및 배지 획득 조건 달성시 획득 로직 추가
  src/main/java/today/sesac/versebyverse/VerseByVerseApplication.java
  src/main/java/today/sesac/versebyverse/badge/entity/Badge.java
  src/main/java/today/sesac/versebyverse/badge/entity/BadgeType.java
  src/main/java/today/sesac/versebyverse/badge/entity/MemberBadge.java
  src/main/java/today/sesac/versebyverse/badge/exception/BadgeErrorCode.java
  src/main/java/today/sesac/versebyverse/badge/exception/BadgeException.java
  src/main/java/today/sesac/versebyverse/badge/repository/BadgeRepository.java
  src/main/java/today/sesac/versebyverse/badge/repository/MemberBadgeRepository.java
  src/main/java/today/sesac/versebyverse/badge/service/BadgeEventListener.java
  src/main/java/today/sesac/versebyverse/badge/service/BadgeService.java
  src/main/java/today/sesac/versebyverse/global/event/MemberCreatedEvent.java
  src/main/java/today/sesac/versebyverse/global/event/PostCreatedEvent.java
  src/main/java/today/sesac/versebyverse/member/controller/MemberController.java
  src/main/java/today/sesac/versebyverse/member/dto/response/MyBadgeListResponseDto.java
  src/main/java/today/sesac/versebyverse/member/dto/response/MyBadgeSummaryDto.java
  src/main/java/today/sesac/versebyverse/member/service/MemberService.java
  src/main/java/today/sesac/versebyverse/post/service/PostCommandService.java
  src/main/resources/data.sql
Labels: Feature

#193 [#125]Feat(신고): 신고 처리 구현 및 커스텀 예외 추가
  src/main/java/today/sesac/versebyverse/comment/entity/Comment.java
  src/main/java/today/sesac/versebyverse/post/entity/Post.java
  src/main/java/today/sesac/versebyverse/report/controller/ReportController.java
  src/main/java/today/sesac/versebyverse/report/dto/request/ReportActionRequestDto.java
  src/main/java/today/sesac/versebyverse/report/dto/response/ReportActionResponseDto.java
  src/main/java/today/sesac/versebyverse/report/dto/response/ReportResponseDto.java
  src/main/java/today/sesac/versebyverse/report/entity/Report.java
  src/main/java/today/sesac/versebyverse/report/exception/ReportErrorCode.java
  src/main/java/today/sesac/versebyverse/report/repository/ReportRepository.java
  src/main/java/today/sesac/versebyverse/report/service/ReportService.java
  src/test/java/today/sesac/versebyverse/post/repository/PostRepositoryTest.java
Labels: Feature

#194 [#191]Fix(config): CORS 설정 스프링 시큐리티 방식으로 변경
  src/main/java/today/sesac/versebyverse/global/config/CorsConfig.java
  src/main/java/today/sesac/versebyverse/global/config/SecurityConfig.java
  src/main/java/today/sesac/versebyverse/global/config/WebConfig.java
Labels: Bug, Feature

#199 [#165]Feat(게시글): 게시글 등록 s3 이미지 파일 업로드
  IMAGE_UPLOAD_README.md
  build.gradle
  src/main/java/today/sesac/versebyverse/global/config/CorsConfig.java
  src/main/java/today/sesac/versebyverse/global/config/S3Config.java
  src/main/java/today/sesac/versebyverse/global/exception/FileUploadException.java
  src/main/java/today/sesac/versebyverse/global/service/S3FileService.java
  src/main/java/today/sesac/versebyverse/post/controller/PostCommandController.java
  src/main/java/today/sesac/versebyverse/post/dto/request/PostCreateRequestDto.java
  src/main/java/today/sesac/versebyverse/post/service/PostCommandService.java
  src/main/java/today/sesac/versebyverse/report/repository/ReportRepository.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/resources/application.yml
Labels: Feature

#197 [#123]Refator(AI): 프롬프트 md파일 내용 수정 및 Concept -> Genre 클래스명,변수명 변경 ✛ 장르타입에 따라 프롬프트타입 매핑하는 util클래스 추가
  src/main/java/today/sesac/versebyverse/ai/dto/request/CommentAiRequestDto.java
  src/main/java/today/sesac/versebyverse/ai/dto/request/PostAiRequestDto.java
  src/main/java/today/sesac/versebyverse/ai/dto/response/CommentAiResponseDto.java
  src/main/java/today/sesac/versebyverse/ai/dto/response/PostAiResponseDto.java
  src/main/java/today/sesac/versebyverse/ai/prompt/PromptType.java
  src/main/java/today/sesac/versebyverse/ai/service/CommentAiService.java
  src/main/java/today/sesac/versebyverse/ai/service/PostAiService.java
  src/main/java/today/sesac/versebyverse/ai/util/GenrePromptMapper.java
  src/main/java/today/sesac/versebyverse/comment/service/CommentService.java
  src/main/java/today/sesac/versebyverse/global/domain/Concept.java
  src/main/java/today/sesac/versebyverse/global/domain/Genre.java
  src/main/java/today/sesac/versebyverse/member/dto/response/MyPostSummaryDto.java
  src/main/java/today/sesac/versebyverse/post/controller/PostQueryController.java
  src/main/java/today/sesac/versebyverse/post/dto/request/PostCreateRequestDto.java
  src/main/java/today/sesac/versebyverse/post/dto/response/PostSingleQueryResponseDto.java
  src/main/java/today/sesac/versebyverse/post/dto/response/PostSummaryResponseDto.java
  src/main/java/today/sesac/versebyverse/post/entity/Post.java
  src/main/java/today/sesac/versebyverse/post/exception/PostErrorCode.java
  src/main/java/today/sesac/versebyverse/post/repository/PostRepository.java
  src/main/java/today/sesac/versebyverse/post/service/PostCommandService.java
  src/main/java/today/sesac/versebyverse/post/service/PostQueryService.java
  src/main/resources/data.sql
  src/main/resources/templates/comment_book_review.md
  src/main/resources/templates/comment_classical_literature.md
  src/main/resources/templates/comment_column.md
  src/main/resources/templates/comment_commentary.md
  src/main/resources/templates/comment_concept_transform.md
  src/main/resources/templates/comment_contribution.md
  src/main/resources/templates/comment_essay.md
  src/main/resources/templates/comment_hipster_feed.md
  src/main/resources/templates/comment_midnight_radio.md
  src/main/resources/templates/comment_modern_literature.md
  src/main/resources/templates/emotion_analysis.md
  src/main/resources/templates/post_book_review.md
  src/main/resources/templates/post_classical_literature.md
  src/main/resources/templates/post_column.md
  src/main/resources/templates/post_commentary.md
  src/main/resources/templates/post_concept_transform.md
  src/main/resources/templates/post_contribution.md
  src/main/resources/templates/post_essay.md
  src/main/resources/templates/post_hipster_feed.md
  src/main/resources/templates/post_midnight_radio.md
  src/main/resources/templates/post_modern_literature.md
  src/main/resources/templates/post_modern_poetry.md
  src/main/resources/templates/profanity_refine.md
  src/test/java/today/sesac/versebyverse/comment/controller/CommentControllerTest.java
  src/test/java/today/sesac/versebyverse/post/repository/PostRepositoryTest.java
Labels: Feature, Refactor

#207 [#176]Feat(preview): 게시판 미리 보기 기능 구현
  src/main/java/today/sesac/versebyverse/post/controller/PostProofreadController.java
  src/main/java/today/sesac/versebyverse/post/dto/request/PostProofreadCreateRequestDto.java
  src/main/java/today/sesac/versebyverse/post/dto/request/PostProofreadPublishRequestDto.java
  src/main/java/today/sesac/versebyverse/post/dto/response/PostProofreadCreateResponseDto.java
  src/main/java/today/sesac/versebyverse/post/entity/PostProofreadAttempt.java
  src/main/java/today/sesac/versebyverse/post/entity/PostProofreadTask.java
  src/main/java/today/sesac/versebyverse/post/entity/TaskStatus.java
  src/main/java/today/sesac/versebyverse/post/exception/PostProofReadErrorCode.java
  src/main/java/today/sesac/versebyverse/post/exception/PostProofReadException.java
  src/main/java/today/sesac/versebyverse/post/repository/PostProofreadAttemptRepository.java
  src/main/java/today/sesac/versebyverse/post/repository/PostProofreadTaskRepository.java
  src/main/java/today/sesac/versebyverse/post/service/PostProofreadService.java
Labels: Feature

#209 [#208]Fix(proofRead - preview): Proofread 파일 이름과 클래스 이름 불일치로 실행 불가해 수정
  src/main/java/today/sesac/versebyverse/post/exception/PostProofreadErrorCode.java
  src/main/java/today/sesac/versebyverse/post/exception/PostProofreadException.java
Labels: Bug

#211 [#210]Refactor(AI): 프롬프트.md 제약사항 및 내용 수정
  src/main/resources/templates/comment_book_review.md
  src/main/resources/templates/comment_classical_literature.md
  src/main/resources/templates/comment_column.md
  src/main/resources/templates/comment_commentary.md
  src/main/resources/templates/comment_contribution.md
  src/main/resources/templates/comment_essay.md
  src/main/resources/templates/comment_hipster_feed.md
  src/main/resources/templates/comment_midnight_radio.md
  src/main/resources/templates/comment_modern_literature.md
  src/main/resources/templates/post_hipster_feed.md
Labels: Refactor
