Repository SproutJavaSesac/versebyverse-backend, pull requests merged in 2025-06, with the labels that each got.

#4 [#3] Deploy(yml): mysql 연결, docker compose 추가
  .gitignore
  docker-compose.yml
  src/main/resources/application.yml
Labels: Deploy

#21 [#20]Deploy(gradle): test 시 .env 적용 위해 build.gradle 수정
  build.gradle
Labels: Test, Deploy

#15 [#10]Feat(비속어): 비속어,AI 패키지 구조, entity, service, repository 생성
  src/main/java/today/sesac/shoutify/ai/controller/AiController.java
  src/main/java/today/sesac/shoutify/ai/service/AiService.java
  src/main/java/today/sesac/shoutify/profanity/controller/ProfanityController.java
  src/main/java/today/sesac/shoutify/profanity/entity/Profanity.java
  src/main/java/today/sesac/shoutify/profanity/entity/ProfanityCategory.java
  src/main/java/today/sesac/shoutify/profanity/repository/ProfanityRepository.java
  src/main/java/today/sesac/shoutify/profanity/service/ProfanityService.java
Labels: Feature

#22 [#13]Feat(게시글,반응하기): post, reaction entity, repository, service 작성
  src/main/java/today/sesac/shoutify/global/Enum/Emoji.java
  src/main/java/today/sesac/shoutify/post/entity/Post.java
  src/main/java/today/sesac/shoutify/post/repository/PostRespository.java
  src/main/java/today/sesac/shoutify/post/service/PostService.java
  src/main/java/today/sesac/shoutify/reaction/entity/Reaction.java
  src/main/java/today/sesac/shoutify/reaction/repository/ReactionRepository.java
  src/main/java/today/sesac/shoutify/reaction/service/ReactionService.java
Labels: Feature

#35 [#26] fix(게시글): emoji의 타입을 String에서 enum으로 수정
  src/main/java/today/sesac/shoutify/post/entity/Post.java
Labels: bug

#32 [#28]Feat(member): 회원 entity 및 repository, service 패키지 작성
  src/main/java/today/sesac/shoutify/member/entity/Member.java
  src/main/java/today/sesac/shoutify/member/entity/RoleType.java
  src/main/java/today/sesac/shoutify/member/entity/SocialType.java
  src/main/java/today/sesac/shoutify/member/repository/MemberRepository.java
  src/main/java/today/sesac/shoutify/member/service/MemberService.java
Labels: Feature

#19 [#11]Feat(comment): 댓글 Entity, Repository, Service 패키지 작성
  src/main/java/today/sesac/shoutify/comment/domain/Comment.java
  src/main/java/today/sesac/shoutify/comment/repository/CommentRepository.java
  src/main/java/today/sesac/shoutify/comment/service/CommentService.java
Labels: Feature

#38 [#37]Feat(comment): 댓글 엔티티 수정
  src/main/java/today/sesac/shoutify/comment/domain/Comment.java
  src/main/java/today/sesac/shoutify/comment/entity/Comment.java
  src/main/java/today/sesac/shoutify/comment/repository/CommentRepository.java
Labels: Feature

#44 [#23] Deploy(sql): dummy data 추가, 그에 맞춰 docker, yml 설정 수정
  .gitignore
  docker-compose.yml
  mysql-conf/my.cnf
  src/main/resources/application.yml
  src/main/resources/data.sql
Labels: Deploy

#52 [#50] chore(게시글): title을 afterTitle, beforeTitle로 분리
  src/main/java/today/sesac/shoutify/ai/config/AiConfig.java
  src/main/java/today/sesac/shoutify/auth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/today/sesac/shoutify/auth/service/UserPrincipal.java
  src/main/java/today/sesac/shoutify/comment/entity/Comment.java
  src/main/java/today/sesac/shoutify/member/entity/Member.java
  src/main/java/today/sesac/shoutify/member/service/MemberService.java
  src/main/java/today/sesac/shoutify/post/Controller/PostCommandController.java
  src/main/java/today/sesac/shoutify/post/dto/request/PostCreateRequestDto.java
  src/main/java/today/sesac/shoutify/post/dto/response/PostCreateResponseDto.java
  src/main/java/today/sesac/shoutify/post/entity/Post.java
  src/main/java/today/sesac/shoutify/post/service/PostCommandService.java
  src/main/java/today/sesac/shoutify/profanity/entity/Profanity.java
  src/main/java/today/sesac/shoutify/profanity/entity/ProfanityCategory.java
  src/main/java/today/sesac/shoutify/profanity/service/ProfanityService.java
  src/main/resources/data.sql
Labels: Chore
